### ISSUE TITLE
Blazor

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/hello-worlds#118]
By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use.

- [ ] only the most simple basic hello world app
- [ ] remove all tests and commands for tests and dependencies for tests
- [ ] must say "Hello World" on the main component
- [ ] only include the minimal components (1 ideally)
- [ ] no routing, not extras whatsoever
- [ ] no styling
- [ ] nothing else !
- [ ] must work by running `npm install` and `npm start` (or equivalent)
- [ ] must be in the folder named `<tech-name>`
- [ ] add build steps and which folder to serve in the README.md
- [ ] verify that the app once built can be served from whatever folder the built assets are placed in
- [ ] verify that running `npx http-server <your-folder-to-serve>` works
- [ ] verify that a Pull Request doesnt already exist. If it does, feel free to contribute to it.

**Comment by spboyer** [comment]
Blazor has 2 models:

1. Blazor server -  the app is executed on the server from within an ASP.NET Core app. UI updates, event handling, and JavaScript calls are handled over a SignalR connection.
1. Blazor Web Assembly - The app is executed directly on the browser UI thread. UI updates and event handling occur within the same process. The app's assets are deployed as static files to a web server or service capable of serving static content to clients.

See: [Blazor hosting models docs for more info](https://docs.microsoft.com/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1&WT.mc_id=docs-github-shboyer)

The README here is states:

> Hello World apps for JavaScript/HTML/CSS libraries/frameworks!

Is the assumption that the preferred model to be added is the web assembly model?

_Note: `npx` or `npm install` would not apply here for .NET examples :-)_

**Comment by johnpapa** [comment]
Thanks for asking. The Gia is to have each app be a self contained app. Something that can be served by a web server (which is not included here).  So i think web assembly makes sense here.
