### ISSUE TITLE
Vanilla HTML hello world

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/hello-worlds#5]
By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use. 

- [ ] only the most simple basic hello world app
- [ ] must say "Hello World" on the main component
- [ ] only include the minimal components (1 ideally)
- [ ] no routing, not extras whatsoever
- [ ] no styling
- [ ] nothing else !
- [ ] must work by running `npm install` and `npm start` (or equivalent)
- [ ] must add to the readme
- [ ] must be in the folder named `<tech-name>-app`

**Comment by Duraimurugan** [comment]
PR# 26
