### ISSUE TITLE
Hello world using Gridsome

### ISSUE THREAD

**Issue by baskarmib** [johnpapa/hello-worlds#67]
By making a PR you are agreeing to that contributing a hello world project allows the repo/project owner to use the hello world app in examples for their own use.

- [ ] only the most simple basic hello world app
- [ ] remove all tests and commands for tests and dependencies for tests
- [ ] must say "Hello World" on the main component
- [ ] only include the minimal components (1 ideally)
- [ ] no routing, not extras whatsoever
- [ ] no styling
- [ ] nothing else !
- [ ] must work by running `npm install` and `npm start` (or equivalent)
- [ ] must be in the folder named `<tech-name>`
- [ ] add yourself using the all-contributors bot `@allcontributors please add @<your-github-account> for code`
- [ ] add build steps and which folder to serve in the README.md, Serve the `public` folder

**Comment by baskarmib** [comment]
Working on this now.

**Comment by johnpapa** [comment]
there is one in #17

**Comment by baskarmib** [comment]
Cool since I did not find it in open issues. Created one. Thanks for doing this John.
