### ISSUE TITLE
Fix all contributors

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/hello-worlds#75]
No clue what's wrong. even without an rc file, it says the rc file has an error at position 1784

**Comment by gildotdev** [comment]
Sorry, did I somehow cause this by asking the bot to add me? I assumed that's what I needed to do based on the checklist in the PR.

**Comment by johnpapa** [comment]
no, it wasn't you/ I have no idea whats wrong. I even removed the bot and started over and its failing. So I gave up for now.

@manekinekko may take a look and see what I did wrong :)

Once it's working again, you can come back and add yourself.

if it fails again - I may just add people manually.
